
### GET all cards
GET http://localhost:3000/api/cards

### GET a card
GET http://localhost:3000/api/cards/61546f9dbdabfed7a7db8859

### POST a new card
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "gaga": "bambooooo",
    "text": "ono",
    "author": "ooo"
}

### PUT (replace) a card
PUT http://localhost:3000/api/cards/61546f9dbdabfed7a7db8859
Content-Type: application/json

{
    "text": "yep",
    "author": "joooggg"
}



### PATCH (change) a card
PATCH  http://localhost:3000/api/cards/61546f9dbdabfed7a7db8859
Content-Type: application/json

{
    "text": "jolo!!"
}

### DELETE a card

DELETE http://localhost:3000/api/cards/615488e0ea3fa066d29be860